### ISSUE TITLE
Logo SVG décallé

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#10]
Le logo ne s'affiche pas de la même manière dans firefox et dans chrome.
@MattiSG tu as une idée ?

![screen_logo](https://cloud.githubusercontent.com/assets/5861569/13596956/1058d64c-e516-11e5-8b2a-b0f6bf62a906.png)
![screen_logo_2](https://cloud.githubusercontent.com/assets/5861569/13596958/10ebe022-e516-11e5-8eca-7cccca752faf.png)

**Comment by MattiSG** [comment]
T'as de la chance de pas encore avoir mergé #12 sinon je t'aurais référé à ta propre documentation  :stuck_out_tongue: 

https://github.com/sgmap/beta.gouv.fr/blob/gh-pages/CONTRIBUTING.md#modifier-le-logo

**Comment by ThibautGery** [comment]
J'ai essayé mais ça veut pas…
je te propose binomer à ton retour.

**Comment by MattiSG** [comment]
Ok.

**Comment by patama** [comment]
Texte qui sort de la boite sur les reuse en bas de page, avec FF 31.8 sous W7
Visible sur Vitiplantation et La Bonne Boite
![reuse](https://cloud.githubusercontent.com/assets/7804610/13843313/21d7d5a2-ec33-11e5-9b36-8233faaba1fb.PNG)

**Comment by MattiSG** [comment]
@patama Je ne vois pas le rapport avec le logo, était-ce volontaire d'ajouter ce point dans cette issue ?
