### ISSUE TITLE
Bug d'alignement 

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#120]
Avec la dernière version de Firefox, les cartes des services ne sont pas alignées
![screenshot from 2016-06-20 22 32 03](https://cloud.githubusercontent.com/assets/5861569/16225700/5132db1a-37a8-11e6-8e04-51fef7a074a8.png)

**Comment by laem** [comment]
Tu peux fixer ça vite fait en changeant cette règle : 
```
#services .ui.cards > .card > .image {
    padding: 1% 5%;
}
```
