### ISSUE TITLE
Documenter l'API de api.gouv.fr

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#125]
L'API est disponible [api.gouv.fr/api.json](https://api.gouv.fr/api.json) 
 * Faut-il référence l'API en elle-même dans le site en tant qu'API de l'administration ?
 * Faut-il ajouter un simple lien dans le footer avec un swagger ?

**Comment by MattiSG** [comment]
AMA c'est meta, et ça va dans le footer.

**Comment by MattiSG** [comment]
Ça peut être une vraie page API, par contre.

**Comment by ThibautGery** [comment]
j'aime cette idée de reprendre le layout des API mais de mettre un lien dans le footer
