### ISSUE TITLE
Expliquer la différence entre les données (Open Data) et API

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#128]
Proposer une meilleure explication entre le site api.gouv.fr et data.gouv.fr.

**Comment by patama** [comment]
Excellente idée !
Y'a au moins 2 sujets : 
- Distinction entre donnée et donnée ouverte d'une part
- Distinction entre API et jeu de donnée d'autre part.

api.gouv ne catalogue que des données (ouverte et non ouverte) consommables grâce à des api
data.gouv ne catalogue que des jeux de données ouvertes

**Comment by MattiSG** [comment]
> api.gouv ne catalogue que des données consommables

Mmh… on est sûrs de ça ? :wink: Il ne me semblerait pas absurde qu'on ouvre aussi des API en écriture un de ces jours.

À mon avis il faut dans un premier temps se focaliser sur API vs jeu de donnée, car il y a tout un gradient sur ce qui est ouvert ou non.

**Comment by ThibautGery** [comment]
Je rejoins @MattiSG, sur le fait d'insister plus sur le coté API vs jeux de donnée d'autre part, car la première distinction risque de porter à confusion : certaines API offrent des données ouvertes (ex: GeoAPI). 
> api.gouv ne catalogue que des données consommables

Ca m'a pas plus choqué que ça en lisant la phrase mais c'est vrai qu'à terme on espère bien avoir des API pour pousser de la donnée (FC permet de faire ça de façon sécurisée). On doit pouvoir reformuler pour éviter toute confusion.
Je vous propose, dans un premier temps de faire une FAQ et je met ça dans `la différence entre api.gouv.fr et data.gouv.fr`. Si la confuision persiste, on fera une page dédiée avec un lien depuis la home. 
WDYT ?

**Comment by MattiSG** [comment]
Je pense que ça pourrait mériter un paragraphe sur la page d’accueil, en utilisant la comparaison comme un moyen d’expliquer ce qu’est une API par le biais de la comparaison avec la donnée.

**Comment by odtvince** [comment]
> api.gouv ne catalogue que des données (ouverte et non ouverte) consommables grâce à des api

Voilà une formulation bien malheureuse : api.gouv ne catalogue pas des données mais des API.

Il faut qu'on s'extirpe *très* clairement de ce tropisme de la donnée et qu'on rappelle qu'une API est simplement « une interface, un contrat passé entre deux systèmes informatiques pour leur permettre de communiquer. » Cette communication n'a pas nécessairement pour objectif un échange de données.

Le.Taxi est par exemple une API permettant de héler un taxi, pas d'accéder à des données. 

Je suis par conséquent tout aussi mal à l'aise avec la proposition de @ThibautGery : 

> Les [API]({{ site.baseurl }}/qu-est-ce-qu-une-api) sont des interfaces. _**Elles permettent de récupérer la données dont le consommateur a besoin sur le moment présent.**_ Ces données peuvent être ouvertes ou confidentielles

Tout au plus _certaines_ API _peuvent_ permettre de récupérer de la donnée.

**Comment by patama** [comment]
Merci Vincent pour ton commentaire,
la formulation api (...) api est bien sur à remettre dans le contexte de la discussion et à prendre dans son intégralité ;)
Quant au tropisme de la donnée, tu prêches un convaincu, cependant si on analysait les requêtes des visiteurs, je suis persuadé qu'ils viennent chercher sur ce site des données et pas des traitements ou des fonctions (pour utiliser des vieux termes). -> possible de suivre les requêtes effectuées  ?

**Comment by MattiSG** [comment]
Une revue de [ma proposition](https://github.com/sgmap/api.gouv.fr/pull/151#issuecomment-231105216) dans #151 rendrait cette discussion plus actionnable  😄

**Comment by MattiSG** [comment]
Traité dans #162.
