### ISSUE TITLE
Déplacer l'indicateur « featured »

### ISSUE THREAD

**Issue by MattiSG** [sgmap/api.gouv.fr#132]
Pour que les zones de responsabilité soient claires, un service ne devrait pas pouvoir spécifier s'il est _featured_. Il s'agit d'un choix éditorial qui devrait être indépendant du service lui-même.

Dans beta.gouv.fr, par exemple, c'est la page d'index qui spécifie les startups qui sont mises en avant, exactement pour cette raison.

**Comment by ThibautGery** [comment]
Closed with #133
