### ISSUE TITLE
GitHub Pages version is illegal

### ISSUE THREAD

**Issue by MattiSG** [sgmap/api.gouv.fr#135]
According to the README:
```
gem install github-pages -v 2.4.8
```

But:

```
$ gem install --user github-pages -v 2.4.8
ERROR:  Could not find a valid gem 'github-pages' (= 2.4.8) in any repository
```

**Comment by MattiSG** [comment]
Je suggère de regarder le mécanisme de validation de version de sgmap/beta.gouv.fr, qui est assez robuste maintenant.

**Comment by ThibautGery** [comment]
Hum le readme est pas à jour, il suffit de faire `bundle install`
