### ISSUE TITLE
Rendre découvrable les API par une machine avec une méta-API 

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#142]
Possibilité :
 * [apisjson]
 * [json-ld]
 * [json-ld] + [hydra]

[json-ld]: http://json-ld.org/
[apisjson]: http://apisjson.org/
[hydra]: https://www.hydra-cg.com/spec/latest/core/

**Comment by jdesboeufs** [comment]
Est-ce qu'il y a une demande utilisateur ?

**Comment by MattiSG** [comment]
Qu'entends-tu par « API sémantique » ?

**Comment by ThibautGery** [comment]
@jdesboeufs Oui on a eu une retours sur twitter et par mail sur notre API mais ce ne sont pas encore des demandes très explicites mais je préfère lancer le débat sur une future API qui va certainement arrivé d'ici peu.
@MattiSG Je sais pas si la future API de api.gouv.fr doit être sémantique mais elle doit à minima être construite intéligemment. Car pour l'instant, elle est plus ou moins inéxistante.

**Comment by MattiSG** [comment]
Ok, mais je ne sais pas ce qu'est une « API sémantique », donc dur pour moi de participer à ce débat  :wink:

**Comment by ThibautGery** [comment]
@MattiSG Roohhh c'est toi qui m'a parlé de ça. Tu fais ça pour m'embêter ;)
Disons qu'il faut qu'on définisse un schéma et s'il pouvait suivre un standard, ça serait mieux (comme json-ld ou même une topologie)

**Comment by MattiSG** [comment]
J’avoue, un peu  :wink:  C’est que cette appellation est ambigüe…

Si on veut maximiser la découvrabilité du sujet, je suggère qu’on renomme l’issue en quelque chose comme « Rendre découvrable les API par une machine avec une méta-API ».

**Comment by MattiSG** [comment]
[HATEOAS](http://putaindecode.io/fr/articles/api/hateoas/) me semble un bon candidat.

**Comment by MattiSG** [comment]
Pourquoi https://api.gouv.fr/api/api-gouv ne suffit-il pas ? Je ferme cette issue tant qu'on n'a pas reçu de demande d'amélioration, comme les utilisateurs y sont invités explicitement sur la page de description.

Pas de souci pour rouvrir si j'ai mal compris l'intention.
