### ISSUE TITLE
Supprimer la marge dans le logo

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#147]
![logo-apigouv](https://cloud.githubusercontent.com/assets/5861569/16383706/8b02ef32-3c86-11e6-9920-c91a55fb0d0c.png)
Supprimer toute la marge à gauche du logo
@MattiSG Je n'ai pas les polices, est-ce que tu peux le regénérer sur ta machine sans la marge ?

**Comment by ThibautGery** [comment]
Si tu pouvais pousser ça dans `add-menu`, ça serait top !

**Comment by MattiSG** [comment]
Done in 89ce6184e2e8f1ae4e2f371e90e60c6fa1756144.

**Comment by ThibautGery** [comment]
Closed by #148
