### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#149]
**Problème** : les usager contacte le site et non les producteur d'API

**Solution** : mettre en évidance un moyen de contact par API

**Comment by jdesboeufs** [comment]
Et peut-être aussi ajouter une page Contact (à l'image de celle de beta.gouv) qui précise quand ne pas contacter le site.

**Comment by ThibautGery** [comment]
En effet c'est une excellente idée

Thibaut

Le mercredi 29 juin 2016, Jérôme Desboeufs <notifications@github.com> a
écrit :

> Et peut-être aussi ajouter une page Contact (à l'image de celle de
> beta.gouv) qui précise quand ne pas contacter le site.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sgmap/api.gouv.fr/issues/149#issuecomment-229404298>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFlwwfUOjkA3Db4291OvjFIloGn7aETpks5qQpeBgaJpZM4JBL6E>
> .
>


-- 
Thibaut Géry
