### ISSUE TITLE
Revoir la catégorisation générale des API

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/api.gouv.fr#177]
Aujourd'hui les APIs sont classées dans 4 catégories :
- [Données confidentielles](https://api.gouv.fr/api/confidential)
- [Données de référence](https://api.gouv.fr/api/reference)
- [Le droit exécutable](https://api.gouv.fr/api/simulation)
- [Big Data](https://api.gouv.fr/api/smartData)

Cette catégorisation est assez décriée aujourd'hui, et je propose qu'on la revoit.

[Données de référence](https://api.gouv.fr/api/reference) devient un fourre-tout où se croisent API de géocodage et API médicaments.
[Big Data](https://api.gouv.fr/api/smartData) est taxé de _bullshit word_

**Comment by jdesboeufs** [comment]
Pourquoi ne pas étudier plutôt une approche _mot-clé_ ?

__Exemple :__
* le.taxi : mobilité, référentiel, temps réel
* Base Adresse Nationale : référentiel, géographie
* GéoAPI : géographie
* API Entreprise : confidentiel
* API Particulier : confidentiel
* OpenFisca : fiscalité, simulateur
* Données Transport Brest Métropole : mobilité, temps réel

**Comment by patama** [comment]
L'usage en terme de recherche est différent entre une taxonomie hiérarchisée et structurée et une indexation par mot clé.

De mon point de vue, c'est très complémentaire et l'utilisateur choisi selon sa démarche de recherche.

**Comment by patama** [comment]
A fermer ?
Les catégories sont supprimées dans la nouvelle mouture du site.
