### ISSUE TITLE
Rendre la recherche plus explicite

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#18]
Il faut comprendre sur quel critère notre recherche a matché

**Comment by MattiSG** [comment]
Origine du besoin ?

**Comment by ThibautGery** [comment]
@MattiSG : ça a été remonté par Patrick et @ppezziardi. Je vais creuser lundi prochain

**Comment by MattiSG** [comment]
:+1:

Documenter l'origine des besoins permet d'obtenir plus de détails si besoin, et de prioriser plus facilement, surtout quand le backlog s'agrandit  :smiley:

**Comment by patama** [comment]
Oui c'était évoqué par plusieurs utilisateurs lors des tests.
Par exemple quand le texte recherché est contenu dans la réponse affiché le mettre en gras

Pas d'idée pour aider l'utilisateur à faire confiance au moteur quand il commence à tapper 3 lettres et reçoit déjà une ou plusieurs réponses où son début de mot n'apparait pas ;)et ne les comprend pas.
exemple en tappant sva, on propose api carto et api particulier ?

**Comment by MattiSG** [comment]
Mmh… C'est des _vrais_ utilisateurs qui tapent `sva` ou des experts qui cherchent à tester les limites du système ?  :wink:
