### ISSUE TITLE
Erreur sur le chargement à partir de la page 501

### ISSUE THREAD

**Issue by AnnabelleCotty** [sgmap/api.gouv.fr#196]
Bonjour, 

Je remarque une erreur de type "Internal Server Error" lorsque je souhaite lancer l'API Datagouv à la page 501.
https://www.data.gouv.fr/api/1/datasets/?page=501
Les 500 premières pages fonctionnent mais pas la suite. 
>> Connaissez-vous la raison? Pouvez-vous svp m'indiquer à quel moment le service sera à nouveau disponible? 

Merci

**Comment by jdesboeufs** [comment]
Bonjour Annabelle.

J'ai relayé auprès de mes collègues de data.gouv.fr.

cc @odtvince @noirbizarre @davidbgk

**Comment by AnnabelleCotty** [comment]
Merci
