### ISSUE TITLE
Update docker-compose conf

### ISSUE THREAD

**Issue by rhanka** [sgmap/api.gouv.fr#203]
docker doesn't build anymore for now

**Comment by Morendil** [comment]
Thanks for the heads-up. We actually had a fix for this committed for a while but forgot to push it to master. But, I'm happy to learn there are other people using Docker to run this code :)

I'm checking this and pushing a PR very soon.

**Comment by Morendil** [comment]
On a second look I'm not sure the above is accurate. What error are you seeing?

**Comment by rhanka** [comment]
The error occurs after the docker build : 

**build
Building app
Step 1/9 : FROM ruby:2.3
 ---> 77356612afa4
Step 2/9 : ENV proxy http://192.168.2.10:3128
 ---> Using cache
 ---> b37aa8a8f699
Step 3/9 : RUN mkdir -p /opt/site
 ---> Using cache
 ---> ae2ea4fb9737
Step 4/9 : RUN gem install -p $proxy github-pages --no-ri --no-rdoc
 ---> Running in 49eca545de46
Successfully installed public_suffix-2.0.5
Successfully installed addressable-2.5.1
Successfully installed colorator-1.1.0
Successfully installed sass-3.4.24
Successfully installed jekyll-sass-converter-1.5.0
Successfully installed rb-fsevent-0.9.8
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.18
Successfully installed rb-inotify-0.9.8
Successfully installed listen-3.0.6
Successfully installed jekyll-watch-1.5.0
Successfully installed kramdown-1.13.2
Successfully installed liquid-3.0.6
Successfully installed mercenary-0.3.6
Successfully installed forwardable-extended-2.6.0
Successfully installed pathutil-0.14.0
Successfully installed rouge-1.11.1
Successfully installed safe_yaml-1.0.4
Successfully installed jekyll-3.4.3
Successfully installed net-dns-0.8.0
Successfully installed ethon-0.10.1
Successfully installed typhoeus-0.8.0
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.12.1
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.7.0
Successfully installed github-pages-health-check-1.3.3
Successfully installed jekyll-redirect-from-0.12.1
Successfully installed jekyll-sitemap-1.0.0
Successfully installed jekyll-feed-0.9.2
Successfully installed jekyll-gist-1.4.0
Successfully installed jekyll-paginate-1.1.0
Successfully installed coffee-script-source-1.12.2
Successfully installed execjs-2.7.0
Successfully installed coffee-script-2.4.1
Successfully installed jekyll-coffeescript-1.0.1
Successfully installed jekyll-seo-tag-2.2.3
Successfully installed jekyll-github-metadata-2.3.1
Successfully installed jekyll-avatar-0.4.2
Successfully installed mini_portile2-2.1.0
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.7.2
Successfully installed i18n-0.8.1
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.3
Successfully installed activesupport-4.2.8
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Successfully installed html-pipeline-2.6.0
Successfully installed gemoji-3.0.0
Successfully installed jemoji-0.8.0
Successfully installed jekyll-mentions-1.2.0
Successfully installed jekyll-relative-links-0.4.0
Successfully installed jekyll-optional-front-matter-0.1.2
Successfully installed jekyll-readme-index-0.1.0
Successfully installed jekyll-default-layout-0.1.4
Successfully installed jekyll-titles-from-headings-0.1.5
Successfully installed minima-2.1.1
Successfully installed jekyll-swiss-0.4.0
Successfully installed jekyll-theme-primer-0.1.8
Successfully installed jekyll-theme-architect-0.0.4
Successfully installed jekyll-theme-cayman-0.0.4
Successfully installed jekyll-theme-dinky-0.0.4
Successfully installed jekyll-theme-hacker-0.0.4
Successfully installed jekyll-theme-leap-day-0.0.4
Successfully installed jekyll-theme-merlot-0.0.4
Successfully installed jekyll-theme-midnight-0.0.4
Successfully installed jekyll-theme-minimal-0.0.4
Successfully installed jekyll-theme-modernist-0.0.4
Successfully installed jekyll-theme-slate-0.0.4
Successfully installed jekyll-theme-tactile-0.0.4
Successfully installed jekyll-theme-time-machine-0.0.4
Successfully installed unicode-display_width-1.2.1
Successfully installed terminal-table-1.8.0
Successfully installed github-pages-138
71 gems installed
 ---> 700b0d53502f
Removing intermediate container 49eca545de46
Step 5/9 : RUN gem install -p $proxy mini_racer
 ---> Running in dcfaa49c2ef7
Successfully installed libv8-5.3.332.38.5-x86_64-linux
Building native extensions.  This could take a while...
Successfully installed mini_racer-0.1.9
2 gems installed
 ---> 064509ac96b7
Removing intermediate container dcfaa49c2ef7
Step 6/9 : WORKDIR /opt/site
 ---> b51d65f8f068
Removing intermediate container 75876c7db69f
Step 7/9 : VOLUME /opt/site
 ---> Running in e093c873f9e4
 ---> 6f501edf28c9
Removing intermediate container e093c873f9e4
Step 8/9 : EXPOSE 4000
 ---> Running in d5431b399a21
 ---> 5588ecacd9fa
Removing intermediate container d5431b399a21
Step 9/9 : CMD jekyll serve --trace --verbose --host 0.0.0.0
 ---> Running in 60e8b4ae993b
 ---> d6d75a4e9b81
Removing intermediate container 60e8b4ae993b
Successfully built d6d75a4e9b81

**run

Creating apidatalabmi_app_1
Attaching to apidatalabmi_app_1
app_1  | /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/resolver.rb:386:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'html-proofer' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/resolver.rb:356:in `each'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/resolver.rb:356:in `verify_gemfile_dependencies_are_found!'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/resolver.rb:203:in `start'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/resolver.rb:182:in `resolve'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:252:in `resolve'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
app_1  | 	from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
app_1  | 	from /usr/local/bundle/gems/jekyll-3.4.3/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
app_1  | 	from /usr/local/bundle/gems/jekyll-3.4.3/exe/jekyll:9:in `<top (required)>'
app_1  | 	from /usr/local/bundle/bin/jekyll:23:in `load'
app_1  | 	from /usr/local/bundle/bin/jekyll:23:in `<main>'
apidatalabmi_app_1 exited with code 1

**Comment by rhanka** [comment]
It seems ok adding : 
```
RUN gem install html-proofer
```
to **Dockerfile**

(sorry for the delay, I spent some time configuring the proxy for ruby in the ministry)

**Comment by Morendil** [comment]
Yes, that will work. It's not ideal as we could avoid the need to list required gems in the Dockerfile and instead use `bundle install`, but that requires adding the `Gemfile` to the image. This type of usage is helped by [Docker multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) but I haven't really practiced them yet.
