### ISSUE TITLE
Contacter service d'attribution accés le.taxi

### ISSUE THREAD

**Issue by QQizi** [sgmap/api.gouv.fr#209]
Bonjour,
Est-il possible d'avoir un mail ou un numéro de contact du service d'attribution des clés d'accés pour l'api le.taxi ?

merci

**Comment by Morendil** [comment]
Oui, vous pouvez adhérer via la [procédure en ligne](https://docs.google.com/forms/d/e/1FAIpQLSdY08d885a4Ps5T2G3kB0pAGx3zFgZqVAER0yHYx5XZ3O4gbQ/viewform?c=0&w=1) ou bien contacter l'équipe à l'adresse indiquée sur la [fiche produit](https://beta.gouv.fr/startup/le-taxi.html).

Je ferme ce ticket car ce dépôt Github n'est pas le bon canal pour les demandes de contact, et vous devriez rapidement trouver un interlocuteur par l'un des deux ci-dessus. Bonne fin de semaine :)
