### ISSUE TITLE
Retour Utilisateurs sur la partie "c'est quoi api.gouv.fr"

### ISSUE THREAD

**Issue by patama** [sgmap/api.gouv.fr#21]
Quelques retours en vrac sur cette partie, actuellement supprimée.

Proposition de plan : 
1. La promesse : simplifier, éviter les doubles saisies, et ne pas donner de justificatifs
2. Le public cible du site : avant tout les utilisateurs d'API, pas que profil dev. (comment je consomme) mais aussi juriste (j'ai le droit d'utiliser ?)
3. les possibilités offertes : accéder à telle ou telle donnée avant utiliser tel ou tel service

Simplifier jugé plus important que authentifier ou géocoder,
Authentifier était jugé trop technique,

**Comment by ThibautGery** [comment]
Aucun changement de fond mais seulement de forme (à vérifier avec des utilisateurs
