### ISSUE TITLE
Evolutions sur la partie 'ils l'utilisent déjà"

### ISSUE THREAD

**Issue by patama** [sgmap/api.gouv.fr#23]
* Faire comme data.gouv : un catalogue de dataset (ici les API)  et un catalogue de reutilisation (ici les 'Services')
* proposer à des éditeurs ou producteurs de services pour une mise en valeur de leur produit : ne mettre en 1st page que quelques réutilisations et un lien "explorer les X réutilisations" en dessous

* proposition d’ajouter la même chose pour les API : mise en valeur de quelques API (les plus utiles ou plus utilisés ou les plus récentes)
* dans la liste des reuses, proposition de faire apparaitre les services au fur et a mesure du scroll (comme des produits sur amazon)

**Comment by ThibautGery** [comment]
Fait au cours de la refonte global (sauf le scroll automatique, qu'on ajoutera quand le nombre de résultat sera trop important)
