### ISSUE TITLE
Evolutions sur la partie liste des API

### ISSUE THREAD

**Issue by patama** [sgmap/api.gouv.fr#24]
Remontées des tests utilisateurs, sur la page actuelle http://sgmap.github.io/api.gouv.fr/api/
* Ajouter un tri, 
  * au moins sur les 4 catégories présentées sur la première page
  * éventuellement sur des tags présent dans le détail d'une api
  * éventuellement avec un champ libre qui filtre dynamiquement les réponses présentées en dessous

**Comment by MattiSG** [comment]
C'était #104.

On a 10 API pour l'instant, la recherche à facettes n'est pas d'actualité, d'autant plus que les propriétés ne sont pas normalisées et qu'il est trop tôt pour faire émerger une ontologie de ces 10 points de données.
