### ISSUE TITLE
Evolutions sur la partie détail d'une API

### ISSUE THREAD

**Issue by patama** [sgmap/api.gouv.fr#25]
Remontées utilisateurs sur les pages de détail de l'ancienne version : 
* Mettre plus d'informations dans le détail
* Mettre systématiquement un lien vers la documentation de l'API
* disponible sous contrat : le contrat est ou ?, que puis je faire/pas faire avec l'API
* ajouter 'cette API est utilisée par XXX'
* ajouter 'pour utiliser cette api, contactez xxx'
* ajouter un bouton 'prévenez moi si les conditions d'utilisation changent'. Ainsi, si cette api devient disponible pour plus de monde, le prospect est averti.
* Est ce que seuls les appels temps réel sont disponibles ? puis je utiliser en batch/lot ?
* quelles sont les étapes pour l'utiliser ?
* il y a deux types d'api : celles qui ont une documentation qqpart et les autres, 
  * pour celles avec de la doc : proposer un guide avec les sujets à couvrir
  * pour celles sans doc proposer un template
Objectif : aider les fournisseurs à donner les informations minimums nécessaire au futur consommateur pour savoir si il peut faire affaire.
* Ajoutez un bouton 'on vous contacte' avec formulaire nom/mail
* Mettre un lien vers une API mock ou demo
* Mettre un lien vers le swagger de l'API
* Augmenter la disticntion entre l'API et ses réutilisations
* Mettre un rappel de la catégorie de l'API (code couleur par ex)

**Comment by ThibautGery** [comment]
Ajouté sauf :

    ajouter 'pour utiliser cette api, contactez xxx'
    ajouter un bouton 'prévenez moi si les conditions d'utilisation changent'. Ainsi, si cette api devient disponible pour plus de monde, le prospect est averti.
    Est ce que seuls les appels temps réel sont disponibles ? puis je utiliser en batch/lot ?
    il y a deux types d'api : celles qui ont une documentation qqpart et les autres,
        pour celles avec de la doc : proposer un guide avec les sujets à couvrir
        pour celles sans doc proposer un template Objectif : aider les fournisseurs à donner les informations minimums nécessaire au futur consommateur pour savoir si il peut faire affaire.
    Ajoutez un bouton 'on vous contacte' avec formulaire nom/mail
    Mettre un lien vers une API mock ou demo

Si un besoin particulier apparait, on ouvre une Issue par point
