### ISSUE TITLE
Trouver les réutilisations grâce à la barre de recherche

### ISSUE THREAD

**Issue by laem** [sgmap/api.gouv.fr#33]
Voir la documentation [search](http://semantic-ui.com/modules/search.html) de semantic-ui.

Distinguer visuellement les réutilisations des APIs.

**Comment by MattiSG** [comment]
Quel est le besoin utilisateur ?

L'objectif principal est de construire l'État plateforme, c'est-à-dire d'ouvrir des API. Pour cela, il faut valoriser les API existantes et aider à en construire d'autres. Pour valoriser les API existantes, il faut les référencer et montrer qu'elles ont un impact. C'est pour cela qu'on ajoute des services.
Pour autant, quel est l'intérêt pour une personne explorant les API de pouvoir chercher des services consommateurs de manière transverse ?

**Comment by laem** [comment]
- "une personne explorant les API"
Quand j'arrive sur le site et que je vois la barre de recherche, rien ne m'indique visuellement qu'elle est destinée à rechercher uniquement des APIs. De plus, le gros titre au-dessus me parle de "fabriquer des services en ligne". Évidemment il y a l'URL `api.gouv.fr`, mais je pense que l'on est tous habitués à interpréter ce genre de champ de recherche comme un champ permettant de tout rechercher. 

- Si j'ai eu connaissance d'un service en ligne qui m'a intéressé et semblé utiliser une API, je vais par exemple chercher "mes aides", qui ne me donnera aucun résultat. J'introduirais donc des facettes dans la recherche pour lister les réutilisations en second.

**Comment by MattiSG** [comment]
Je doute que `api.gouv.fr` soit un point d'entrée pour chercher des services.
Je pense que nous ne devrions pas faire en sorte qu'il le devienne. Les services sont un moyen de valoriser les API, mais le catalogue doit rester un catalogue d'API et non de services.

Je vote pour fermer.

@jdesboeufs @patama @ThibautGery un avis ?

**Comment by jdesboeufs** [comment]
Je vote aussi pour fermer.

**Comment by ThibautGery** [comment]
Pareil !
