### ISSUE TITLE
Liens pointants vers des 404

### ISSUE THREAD

**Issue by patama** [sgmap/api.gouv.fr#39]
Quand on clique sur l'une des 4 api depuis la page http://sgmap.github.io/api.gouv.fr/api/
on a une 404 (par exemple pour api carto http://sgmap.github.io/api/api-carto.html)

PS : Pour arriver sur la page http://sgmap.github.io/api.gouv.fr/api/
je viens de http://api.gouv2.fr/ en cliquant sur "Explorer les 4 api disponibles"

**Comment by ThibautGery** [comment]
Bien vue, c'est très bizarre, on a trop joué avec les redirections, j'ai l'impression... Les liens sont bons.
@MattiSG @jdesboeufs vous avez une idée ?

**Comment by ThibautGery** [comment]
Problème trouvé, je corrige ça demain et je fais un post mortem.
Je pense que notre solution pour mettre du https sans mettre de CNAME est pas viable.

**Comment by jdesboeufs** [comment]
Je peux te garantir qu'elle est viable.
Utilisée en production sur divers sites depuis plusieurs années déja.
C'est la boucle de redirection qui doit déconner, je remarque par exemple
que certains headers HTTP sont litigieux.

**Comment by ThibautGery** [comment]
@jdesboeufs  : Je me demande surtout si le comportement de guthub n'a pas changé car ça fait 2 semaines qu'on a pas changé de version et le principal bouton ne fonctionne plus alors qu'il marchait très bien avant.

Le problème
==========
Il y a un problème lorsque github page fait une redirection.
Si on se rend sur cette URL [api.beta.gouv.fr/api](api.beta.gouv.fr/api) alors on est redirigé avec une 301 vers [sgmap.github.io/api.gouv.fr/api/](http://sgmap.github.io/api.gouv.fr/api/)
Si on se rend sur [api.beta.gouv.fr/api](http://api.beta.gouv.fr/api/)

Les solutions
==========

**Comment by MattiSG** [comment]
J'ai eu un souci similaire sur beta.gouv.fr et ai utilisé un fichier `startups.html` et un dossier `startup/` (au singulier), qui me permet en plus d'avoir des URL accordées en nombre (ok rationalisation a posteriori  :wink:  ).

**Comment by jdesboeufs** [comment]
Oui en mettant les adresses pleines ça doit marcher.
Sinon GitHub corrige et te redirige dans les choux.
À la rigueur le fichier CNAME te permet d'avoir la main et de rediriger à
nouveau vers HTTPS.
Le jeu. 31 mars 2016 à 09:42, Matti Schneider <notifications@github.com> a
écrit :
