### ISSUE TITLE
Réutilisations

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#65]
Le terme réutilisation n'est pas clair, il faut le modifier et/ou ajouter une description de ce que c'est.

C'est remonté des tests utilisateurs fait le 03/05.
Croyance sur le sujet : 
 * Outil pour expliquer les API
 * tutoriel pour les API
 * API mais avec des données bidons

ping @ppezziardi @patama

**Comment by patama** [comment]
Propositions (à discuter / essayer avec de vrais utilisateurs) :

- En laissant Réutilisations, ajouter un infobulle avec une description, par exemple : utilisation d'une ou plusieurs API pour offrir à l'usager un service 
- Remplacer "Réutilisations" par "Services" : pour moi c'est un mot valise pas forcément clair, mais il est utilisé dans les comm' FC-etat plateforme : Fournisseurs de Services par opposition aux Fournisseurs de Données
- "Démarches en ligne" ou "Services Innovants" ?
- "Exemples de services utilisant des API"

**Comment by ThibautGery** [comment]
J'aime bien le terme **Application** car on pense aux applications mobiles qui consomment des API.
On peut ajouter une description du genre :
 > Ces applications utilisent les API afin récupérer les données au bon endroit pour répondre aux besoins des utilisateurs
