### ISSUE TITLE
Plus mettre en valeur le champ de recherche ?

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#68]
Seules la moitié des personnes utilisent la barre de recherche. Doit-on plus la mettre en valeur ?

**Comment by MattiSG** [comment]
Attention, c'est du problémationnage de solution, ça. Il faut comprendre quel est le besoin réel de l'utilisateur, pour comprendre pourquoi cette barre de recherche n'est pas plus utilisée. Et décider s'il faut plus la mettre en avant, ou la jeter, ou accepter qu'elle répond au besoin de 50% des utilisateurs qui savent ce qu'ils cherchent, et que les 50% qui se retrouvent sur ce site par curiosité n'en ont pas l'usage.

**Comment by ThibautGery** [comment]
Pas faux, je vais tenter de découvrir ça avec mes prochains tests utilisateurs
