### ISSUE TITLE
Ajout d'un blog

### ISSUE THREAD

**Issue by ThibautGery** [sgmap/api.gouv.fr#99]
S'inspirer de beta.gouv.fr

**Comment by MattiSG** [comment]
Quelle sera la ligne éditoriale ? Le public ? La fréquence de publication ? Les auteurs autorisés ?

En un mot : pourquoi ?  :wink:

**Comment by ThibautGery** [comment]
@MattiSG Mon besoin est d'ajouter une description de ce qu'est une API avec une métaphore, j'avais réussi à faire comprendre le principe à Fanny. J'ai hésité entre une page statique et un article de blog.

Le public serait le même que api.gouv : 
 * des fonctionnels
 * des chefs de projets
 * des développeurs

Pour la fréquence, j'en sais rien du tout. (c'est bien le problème)
Pour les auteurs toutes les personnes qui soumettent des PR tant que c'est validé par les personnes en charge du projet

**Comment by MattiSG** [comment]
Alors page statique pour l'instant. YAGNI.

**Comment by ThibautGery** [comment]
Pas de besoin pour l'instant, je ferme
